In [46]:
import pandas as pd 
from joblib import  load
clf = load('model_final.joblib')

In [47]:
df = pd.read_csv('test.csv') 

df=df.drop(['Id','Alley','PoolQC','Fence','MiscFeature'], axis = 1)

In [48]:
df=pd.get_dummies(df,drop_first=True)

In [52]:
df.loc[:, [222,223, 224,225,226,227,228,229,230,231,232,233,235,236,237,238]]=0

In [53]:
df

,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,BsmtFinSF2,...,228,229,230,231,232,233,235,236,237,238
0,20,80.0,11622,5,6,1961,1961,0.0,468.0,144.0,...,0,0,0,0,0,0,0,0,0,0
1,20,81.0,14267,6,6,1958,1958,108.0,923.0,0.0,...,0,0,0,0,0,0,0,0,0,0
2,60,74.0,13830,5,5,1997,1998,0.0,791.0,0.0,...,0,0,0,0,0,0,0,0,0,0
3,60,78.0,9978,6,6,1998,1998,20.0,602.0,0.0,...,0,0,0,0,0,0,0,0,0,0
4,120,43.0,5005,8,5,1992,1992,0.0,263.0,0.0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1454,160,21.0,1936,4,7,1970,1970,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
1455,160,21.0,1894,4,5,1970,1970,0.0,252.0,0.0,...,0,0,0,0,0,0,0,0,0,0
1456,20,160.0,20000,5,7,1960,1996,0.0,1224.0,0.0,...,0,0,0,0,0,0,0,0,0,0
1457,85,62.0,10441,5,5,1992,1992,0.0,337.0,0.0,...,0,0,0,0,0,0,0,0,0,0
1458,60,74.0,9627,7,5,1993,1994,94.0,758.0,0.0,...,0,0,0,0,0,0,0,0,0,0

In [54]:
y_predict=clf.predict(df)

In [55]:
y_predict

array([150540.63380012, 156493.69846737, 179913.67208052, ...,
       176573.37488739, 148413.47494516, 210912.17452233])

In [56]:
pred=pd.DataFrame(y_predict)
pred.columns =['SalePrice']
sub_df=pd.read_csv('sample_submission.csv')
datasets=pd.concat([sub_df['Id'],pred],axis=1)

datasets.to_csv('sample_submission1.csv',index=False)